### ISSUE TITLE
Move comment exporting functions out of typemap.Registry

### ISSUE THREAD

**Issue by sagikazarmark** [twitchtv/protogen#1]
As far as I can tell those are pure functions and there is no need for having them in the registry. In fact that makes using them harder.

What do you think?

(BTW: 👍 for extracting these packages from twirp/internal)

**Comment by spenczar** [comment]
Yes, this definitely sounds like a good idea. This package was put together on the fly and without attention to hygiene like this. I'd happily accept a PR.
